name: CD

on:
  push:
    branches:
      - "main"

jobs:
  arm-32-release:
    runs-on: ubuntu-latest
    env:
      BIN: otop
      TARGET: arm-unknown-linux-gnueabihf
      FRONT_DIR: "packages/frontend"
      BACK_DIR: "packages/backend"
    steps:
      - name: Setting up environment
        run: |
          cargo install cross
      - uses: actions/setup-node@v4
        with:
          node-version: 16.17
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build Backend
        run: |
          cross build --manifest-path $BACK_DIR/Cargo.toml --target $TARGET --release --verbose
      - name: Build Frontend
        run: |
          npm install --prefix $FRONT_DIR;
          npm run build --prefix $FRONT_DIR;
      - name: Creating Zip
        run: |
          mkdir otop/bin -p;
          mv $BACK_DIR/target/$TARGET/release/$BIN otop/bin/;
          mv $FRONT_DIR/dist otop/www;
          zip otop.zip otop -r;
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest-arm-32"
          prerelease: true
          title: "ARM 32 Bit release"
          files: |
            otop.zip
  x86-64-release:
    runs-on: ubuntu-latest
    env:
      BIN: otop
      BIN_DIR: "target/release"
      FRONT_DIR: "packages/frontend"
      BACK_DIR: "packages/backend"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 16.17
      - name: Build Backend
        run: cargo build --manifest-path packages/backend/Cargo.toml --release --verbose
      - name: Build Frontend
        run: |
          npm install --prefix $FRONT_DIR;
          npm run build --prefix $FRONT_DIR;
      - name: Creating Zip
        run: |
          mkdir otop/bin -p;
          mv $BACK_DIR/target/release/$BIN otop/bin/;
          mv $FRONT_DIR/dist otop/www;
          zip otop.zip otop -r;
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest-x86-64"
          prerelease: true
          title: "x86 64 Bit release"
          files: |
            otop.zip
